basePath: '{{.BasePath}}'
definitions:
  requests.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
host: '{{.Host}}'
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: '"This is a simple authentication service"'
  title: Go Auth Service
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with the input payload
      parameters:
      - description: User for login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Login
      tags:
      - Users
swagger: "2.0"
